### ISSUE TITLE
Document versioning system

### ISSUE THREAD

**Issue by ItsHarper** [OpenFTC/OpenFTC-app#9]
The turbo repo kind of has a tacked-on "turbo version". We need to integrate that with the main repo somehow, decide on if/how we want to express that in versionName, etc. If we're publishing to Google Play, that will affect this. (#10)

Do we want to keep the versionCode in sync? If we don't, the user will always have to uninstall the app before installing the stock version. That could be a good thing. It would mean we don't have to worry about maintaining compatibility with the official release for anything in our app's directory (though of course not the FIRST one). It would also prevent us from having to worry about downgrades of our app. I'm not really seeing any downsides.

**Comment by Windwoes** [comment]
Yeah I think syncing the version codes would be too much trouble

**Comment by ItsHarper** [comment]
It wouldn't be any trouble. We just never touch versionCode. It only gets updated when FTC updates it.

**Comment by ItsHarper** [comment]
Definitely switch to a proper BuildConfig for the OpenFTC module. We want RobotLog.logBuildConfig() to be safe to use.

**Comment by WardBenjamin** [comment]
As long as the three required variables are present, the OpenFTC class is logged identically to any BuildConfig class, since RobotLog just pulls the three named static variables.

**Comment by WardBenjamin** [comment]
Because of our dependency on the official ftc_app version, I would suggest following the Electron versioning system (a variant of SemVer due to Electron needing to follow version updates of it's Chromium and Node dependencies):

# Electron Versioning

Due to its dependency on Node and Chromium, it is not possible for the Electron project to adhere to a SemVer policy. You should therefore always reference a specific version of Electron.

## Electron version numbers are bumped using the following rules:

**Major** is for breaking changes in Electron’s API. If you upgrade from 0.37.0 to 1.0.0, you will have to make changes to your app.
**Minor** is for major Chrome and minor Node upgrades, or significant Electron changes. If you upgrade from 1.5.0 to 1.6.0, your app is supposed to still work, but you might have to work around small changes.
**Patch** is for new features and bug fixes. If you upgrade from 1.6.2 to 1.6.3, your app will continue to work as-is.

Source: https://electron.atom.io/docs/tutorial/electron-versioning/

**Comment by ItsHarper** [comment]
For OpenFTC-turbo, I'm not sure it makes sense to have a separate "turbo version". I think that's kind of confusing, especially when the way things are set up results in a variable called `VERSION_COMPLETE` with a value of `OpenFTC-turbo 1.0`. Is that 1.0 for the Turbo Version or 1.0 for the OpenFTC version? I'd like to have one value that contains everything you need to know about the version of OpenFTC in use. 

My proposal is that we get rid of the "Turbo version", and keep the version numbers the same between them. In the rare case where we want to make a new release only for the Turbo version, we simply append `-1` to the end of the OpenFTC version number. @FROGbots-4634, the "Turbo version" was your idea, so I'd like to hear your thoughts especially.

**Comment by Windwoes** [comment]
Well I feel like the Turbo version is good because we may need to be removing more and more stuff as time goes on. For example, I've been meaning to nuke the 2016-17 Vuforia target files but I haven't PRed yet.

**Comment by ItsHarper** [comment]
Yeah, but it's confusing to see "OpenFTC-turbo 1.5" (made-up version numbers here) on the main screen and then "Turbo version: 1.1" on the about screen. I don't see why we need a separate number to track it. If a user is running OpenFTC-turbo version 1.5, we already know what changes to the "turbo" part that includes, and so will the user if they look at the release notes.

**Comment by ItsHarper** [comment]
I think we should say that "minor" version bumps indicate either a new version of the official SDK has been included, OR a new OpenFTC feature was added that changes something big.

For example, DSktop support would be a "patch" bump, and the ability to build a stock APK from an OpenFTC project would be a "minor" bump.
